kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: si
spec:
  host: {{ .Values.host }}
  to:
    kind: Service
    name: example
  port:
    targetPort: 8080
  tls:
    termination: edge
